[DEFAULT]
n_clients= 100
lambda_c = 8
n_hops = 5

[TOPOLOGY]
#Topology can take stratified, cascade/XRD, free route , ba topology , cyclic_stratified, grid
type = grid
fully_connected = False

#Routing can be source, hopbyhop, larmix
; Note: routing = larmix is feasible for stratified and free route topologies only
routing = source

# Grid topology specific parameters
grid_width = 10
grid_height = 10
mix_as_client = True

# If routing 
latency_bound = 20.0
E2E = 1
n_layers = 1

#If stratified 
l_mixes_per_layer = 10

# If routing = larmix, 
; tau-> 0 means deterministic lowest latency path 
; tau-> 1 means uniform random path
tau = 0.5
balancing = greedy



#If Cascades
n_cascades = 3

# If Barabasi Albert (BA) topology
m_fully_connected_mixes = 3


[MIXING]
#mix_type takes poisson, time, or pool
mix_type = pool
mu = 1.0
timeout = 2
threshold = 50
# values from 0 to 1
flush_percent = 0.1
[DUMMIES]
client_dummies = False
rate_client_dummies = 1
link_based_dummies = False
multiple_hop_dummies = False
rate_mix_dummies = 1
[NODES_SELETION]
#Probability over nodes selection: uniform, specific
probability = Uniform
#if specific
    #if topology = stratified
w_mix_l1 = [0.5]
w_mix_l2 = [0.3]
w_mix_l3 = [0.1]
    #if topology = cascade
w_cascades = [0.8, 0.1, 0.1]

[THREATMODEL]
# Number of corrupted mixes
corrupt_mixes = 0
balanced_corruption = False